project_id = "xyhgckqxowqnzjtoblfs"

[functions.hws-send-disturbance-report]
verify_jwt = false

[functions.hws-generate-invoice-pdf]
verify_jwt = false

[functions.hws-send-invitation]
verify_jwt = false

[functions.hws-create-team-time-entries]
verify_jwt = false

[functions.hws-whatsapp-webhook]
verify_jwt = false

[functions.hws-whatsapp-daily-reminder]
verify_jwt = false

[functions.hws-create-user]
verify_jwt = false

[functions.hws-whatsapp-onboarding]
verify_jwt = false

[functions.hws-whatsapp-cleanup]
verify_jwt = false

[functions.hws-daily-error-digest]
verify_jwt = false

[functions.hws-delete-user]
verify_jwt = false

[functions.hws-forgot-password-whatsapp]
verify_jwt = false

[functions.hws-sync-assignment-to-calendar]
verify_jwt = false

[functions.hws-parse-invoice-document]
verify_jwt = false